/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontEnd.tabelas;

import static ferramentas.CrudCliente.listarCliente;

import java.util.List;

import javax.swing.SwingUtilities;

import dados.Cliente;
import dados.Venda;
import dados.Video;
import frontEnd.telas.ClienteTela;
import frontEnd.telas.VideoTela;

/**
 *
 * @author gbert
 */
public class TabelaCliente extends javax.swing.JPanel {

    /**
     * Creates new form TabelaCliente
     */
    List<dados.Cliente> clientes; // armazena a lista carregada

    public TabelaCliente() {
        initComponents();
        configurarTabela();
    }

    private void configurarTabela() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] { "Nome", "Telefone", "Multa De atraso" }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // impede edição por clique/duplo-clique
            }
        });
    }

    public void carregarClientes(List<dados.Cliente> clientes) {
        this.clientes = clientes; // guarda a lista para uso no clique
        javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1
                .getModel();
        model.setRowCount(0); // limpa tabela

        for (dados.Cliente c : clientes) {
            model.addRow(new Object[] { c.getNome(), c.getTelefone(), "R$ " + c.getMultaAtraso() });
        }
    }

    public void atualizarTabela() {
        List<Cliente> listaAtualizada = listarCliente();
        carregarClientes(listaAtualizada);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Lista de Cliente");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null },
                        { null, null, null, null }
                },
                new String[] {
                        "id", "nome", "telefone", "Multa de atraso"
                }));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel1)
                                                .addGap(0, 0, Short.MAX_VALUE))
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621,
                                                Short.MAX_VALUE))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(jLabel1)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 507, Short.MAX_VALUE)
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            int viewRow = jTable1.getSelectedRow();
            if (viewRow == -1)
                return;

            int modelRow = jTable1.convertRowIndexToModel(viewRow);
            if (modelRow < 0 || modelRow >= clientes.size())
                return;

            final Cliente c = clientes.get(modelRow);
            SwingUtilities.invokeLater(() -> {
                ClienteTela tela = new ClienteTela(c, this::atualizarTabela);
                tela.setLocationRelativeTo(null);
                tela.setVisible(true);
            });
        }
    }// GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
