/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontEnd.tabelas;

import dados.Cliente;
import dados.Game;
import dados.Produto;
import dados.Venda;
import dados.Video;
import frontEnd.telas.ClienteTela;
import frontEnd.telas.JogoTela;
import frontEnd.telas.VendaTela;

import javax.swing.*;
import javax.swing.table.DefaultTableModel;

import static ferramentas.CrudVendas.listarVendas;

import java.util.ArrayList;
import java.util.List;

/**
 *
 * @author gbert
 */
public class TabelaVendas extends javax.swing.JPanel {

    /**
     * Creates new form TabelaVendas
     */
    private List<Venda> vendas = new ArrayList<Venda>();

    public TabelaVendas() {
        initComponents();
        configurarTabela();
    }

    private void configurarTabela() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] { "ID", "Telefone do cliente", "ID do produto", "Data da locação",
                        "Data limite de devolução", "Valor da venda" }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // impede edição por clique/duplo-clique
            }
        });
        jTable1.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jTable1.getTableHeader().setReorderingAllowed(false);
    }

    public void carregarVendas(List<Venda> vendas) {
        this.vendas = vendas; // guarda a lista para uso no clique
        DefaultTableModel model = (DefaultTableModel) jTable1.getModel();
        model.setRowCount(0); // limpa tabela

        for (Venda v : vendas) {
            model.addRow(new Object[] {
                    v.getCodigo(),
                    v.getIdCliente(), // mostra o telefone do cliente
                    v.getIdProduto(), // mostra o id do produto
                    v.getDataLocar(),
                    v.getDataDevol(),
                    "R$ " + v.getValorTotal()
            });
        }
    }

    public void atualizarTabela() {
        List<Venda> listaAtualizada = listarVendas();

        carregarVendas(listaAtualizada);
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        jLabel1.setText("Lista de Vendas");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel1)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 727, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 471, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            int viewRow = jTable1.getSelectedRow();
            if (viewRow == -1) return;

            int modelRow = jTable1.convertRowIndexToModel(viewRow);
            if (modelRow < 0 || modelRow >= vendas.size()) return;

            final Venda v = vendas.get(modelRow);
            SwingUtilities.invokeLater(() -> {
                VendaTela tela = new VendaTela(v, this::atualizarTabela);
                tela.setLocationRelativeTo(null);
                tela.setVisible(true);
            });
        }
    }//GEN-LAST:event_jTable1MouseClicked

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
