/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontEnd.formularios;

import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

/**
 *
 * @author gbert
 */
public class FormularioJogo extends javax.swing.JPanel {

    /**
     * Creates new form FomularioJogo
     */
    public FormularioJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        grupoBotoesClassificacao = new javax.swing.ButtonGroup();
        lTitulo = new javax.swing.JLabel();
        fomularioContainer = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lDesenvolvedora = new javax.swing.JLabel();
        tfDesenvolvedora = new javax.swing.JTextField();
        lPublicadora = new javax.swing.JLabel();
        tfPublicadora = new javax.swing.JTextField();
        lPlataforma = new javax.swing.JLabel();
        tfPlataforma = new javax.swing.JTextField();
        lClassificacao = new javax.swing.JLabel();
        jrbLivre = new javax.swing.JRadioButton();
        jrb12 = new javax.swing.JRadioButton();
        jrb16 = new javax.swing.JRadioButton();
        jrb10 = new javax.swing.JRadioButton();
        jrb14 = new javax.swing.JRadioButton();
        jrb18 = new javax.swing.JRadioButton();
        botaoEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(500, 600));
        setPreferredSize(new java.awt.Dimension(500, 600));

        lTitulo.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        lTitulo.setText("Fomulario cadastro de jogos");

        fomularioContainer.setBackground(new java.awt.Color(204, 204, 204));
        fomularioContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        fomularioContainer.setLayout(new java.awt.GridBagLayout());

        lNome.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lNome.setText("Nome do jogo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(35, 11, 0, 0);
        fomularioContainer.add(lNome, gridBagConstraints);

        tfNome.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfNome.setToolTipText("Digite o nome do jogo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 45;
        gridBagConstraints.ipadx = 402;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 11);
        fomularioContainer.add(tfNome, gridBagConstraints);

        lDesenvolvedora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lDesenvolvedora.setText("Desenvolvedora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 0);
        fomularioContainer.add(lDesenvolvedora, gridBagConstraints);

        tfDesenvolvedora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfDesenvolvedora.setToolTipText("Digite a desenvolvedora do jogo");
        tfDesenvolvedora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDesenvolvedoraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 45;
        gridBagConstraints.ipadx = 402;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 11);
        fomularioContainer.add(tfDesenvolvedora, gridBagConstraints);

        lPublicadora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lPublicadora.setText("Publicadora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 0);
        fomularioContainer.add(lPublicadora, gridBagConstraints);

        tfPublicadora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfPublicadora.setToolTipText("Digite o nome da publicadora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 45;
        gridBagConstraints.ipadx = 402;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 11);
        fomularioContainer.add(tfPublicadora, gridBagConstraints);

        lPlataforma.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lPlataforma.setText("Plataforma");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 0, 0);
        fomularioContainer.add(lPlataforma, gridBagConstraints);

        tfPlataforma.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfPlataforma.setToolTipText("Digite o nome da plataforma do jogo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 45;
        gridBagConstraints.ipadx = 402;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 11);
        fomularioContainer.add(tfPlataforma, gridBagConstraints);

        lClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lClassificacao.setText("Classificação indicativa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 21;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 11, 0, 0);
        fomularioContainer.add(lClassificacao, gridBagConstraints);

        grupoBotoesClassificacao.add(jrbLivre);
        jrbLivre.setLabel("livre");
        jrbLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbLivreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 0);
        fomularioContainer.add(jrbLivre, gridBagConstraints);

        grupoBotoesClassificacao.add(jrb12);
        jrb12.setLabel("12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 9;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 2, 0, 0);
        fomularioContainer.add(jrb12, gridBagConstraints);

        grupoBotoesClassificacao.add(jrb16);
        jrb16.setLabel("16");
        jrb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb16ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 42;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        fomularioContainer.add(jrb16, gridBagConstraints);

        grupoBotoesClassificacao.add(jrb10);
        jrb10.setLabel("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 2;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        fomularioContainer.add(jrb10, gridBagConstraints);

        grupoBotoesClassificacao.add(jrb14);
        jrb14.setLabel("14");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        fomularioContainer.add(jrb14, gridBagConstraints);

        grupoBotoesClassificacao.add(jrb18);
        jrb18.setLabel("18");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 43;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        fomularioContainer.add(jrb18, gridBagConstraints);

        botaoEnviar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoEnviar.setText("Enviar");
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 42;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 93, 0);
        fomularioContainer.add(botaoEnviar, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Preço");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 0, 0);
        fomularioContainer.add(jLabel1, gridBagConstraints);

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextField1.setToolTipText("preço");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 45;
        gridBagConstraints.ipadx = 402;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 11);
        fomularioContainer.add(jTextField1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lTitulo)
                .addContainerGap(167, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fomularioContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(fomularioContainer, javax.swing.GroupLayout.PREFERRED_SIZE, 514, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(36, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfDesenvolvedoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDesenvolvedoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDesenvolvedoraActionPerformed

    private void jrbLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbLivreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbLivreActionPerformed

    private void jrb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb16ActionPerformed

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
        String nome = tfNome.getText();
        String desenvolvedora = tfDesenvolvedora.getText();
        String plataforma = tfPlataforma.getText();
        String publicadora = tfPlataforma.getText();
        ButtonModel classificacao = grupoBotoesClassificacao.getSelection();
        JOptionPane.showMessageDialog(fomularioContainer, "Jogo " + nome + " Criado");
    }//GEN-LAST:event_botaoEnviarActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JPanel fomularioContainer;
    private javax.swing.ButtonGroup grupoBotoesClassificacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton jrb10;
    private javax.swing.JRadioButton jrb12;
    private javax.swing.JRadioButton jrb14;
    private javax.swing.JRadioButton jrb16;
    private javax.swing.JRadioButton jrb18;
    private javax.swing.JRadioButton jrbLivre;
    private javax.swing.JLabel lClassificacao;
    private javax.swing.JLabel lDesenvolvedora;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPlataforma;
    private javax.swing.JLabel lPublicadora;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JTextField tfDesenvolvedora;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPlataforma;
    private javax.swing.JTextField tfPublicadora;
    // End of variables declaration//GEN-END:variables
}
