/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontEnd.formularios;

/**
 *
 * @author gbert
 */
public class FormularioVideo extends javax.swing.JPanel {

    /**
     * Creates new form FomularioFilme
     */
    public FormularioVideo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        lTitulo = new javax.swing.JLabel();
        formularioContainer = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lEstudio = new javax.swing.JLabel();
        tfEstudio = new javax.swing.JTextField();
        lDistribuidora = new javax.swing.JLabel();
        tfDistribuidora = new javax.swing.JTextField();
        lFormato = new javax.swing.JLabel();
        tfFormato = new javax.swing.JTextField();
        lTipoMidia = new javax.swing.JLabel();
        tfTipoMidia = new javax.swing.JTextField();
        lDuraco = new javax.swing.JLabel();
        tfDuracao = new javax.swing.JTextField();
        lPreco = new javax.swing.JLabel();
        tfPreco = new javax.swing.JTextField();
        lClassificacao = new javax.swing.JLabel();
        jrbLivre = new javax.swing.JRadioButton();
        jrb10 = new javax.swing.JRadioButton();
        jrb12 = new javax.swing.JRadioButton();
        jrb14 = new javax.swing.JRadioButton();
        jrb16 = new javax.swing.JRadioButton();
        jrb18 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(500, 650));
        setPreferredSize(new java.awt.Dimension(500, 650));

        lTitulo.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        lTitulo.setText("Formulario Cadastro de video");

        formularioContainer.setBackground(new java.awt.Color(204, 204, 204));
        formularioContainer.setLayout(new java.awt.GridBagLayout());

        lNome.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lNome.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 0);
        formularioContainer.add(lNome, gridBagConstraints);

        tfNome.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfNome.setToolTipText("Digite o nome do jogo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 47;
        gridBagConstraints.ipadx = 412;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        formularioContainer.add(tfNome, gridBagConstraints);

        lEstudio.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lEstudio.setText("Estudio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        formularioContainer.add(lEstudio, gridBagConstraints);

        tfEstudio.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfEstudio.setToolTipText("Digite a desenvolvedora do jogo");
        tfEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEstudioActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 47;
        gridBagConstraints.ipadx = 412;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        formularioContainer.add(tfEstudio, gridBagConstraints);

        lDistribuidora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lDistribuidora.setText("Distribuidora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        formularioContainer.add(lDistribuidora, gridBagConstraints);

        tfDistribuidora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfDistribuidora.setToolTipText("Digite o nome da publicadora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 47;
        gridBagConstraints.ipadx = 412;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        formularioContainer.add(tfDistribuidora, gridBagConstraints);

        lFormato.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lFormato.setText("Formato");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        formularioContainer.add(lFormato, gridBagConstraints);

        tfFormato.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfFormato.setToolTipText("Digite o nome da plataforma do jogo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 47;
        gridBagConstraints.ipadx = 412;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        formularioContainer.add(tfFormato, gridBagConstraints);

        lTipoMidia.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lTipoMidia.setText("Tipo de midia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 13;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        formularioContainer.add(lTipoMidia, gridBagConstraints);

        tfTipoMidia.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfTipoMidia.setToolTipText("preço");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 47;
        gridBagConstraints.ipadx = 412;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        formularioContainer.add(tfTipoMidia, gridBagConstraints);

        lDuraco.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lDuraco.setText("Duração");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        formularioContainer.add(lDuraco, gridBagConstraints);

        tfDuracao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfDuracao.setToolTipText("preço");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 47;
        gridBagConstraints.ipadx = 412;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        formularioContainer.add(tfDuracao, gridBagConstraints);

        lPreco.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lPreco.setText("Preço");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        formularioContainer.add(lPreco, gridBagConstraints);

        tfPreco.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfPreco.setToolTipText("preço");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 47;
        gridBagConstraints.ipadx = 412;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        formularioContainer.add(tfPreco, gridBagConstraints);

        lClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lClassificacao.setText("Classificação indicativa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 22;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 6, 0, 0);
        formularioContainer.add(lClassificacao, gridBagConstraints);

        jrbLivre.setLabel("livre");
        jrbLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbLivreActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        formularioContainer.add(jrbLivre, gridBagConstraints);

        jrb10.setLabel("10");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 6;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 14;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 0, 0, 0);
        formularioContainer.add(jrb10, gridBagConstraints);

        jrb12.setLabel("12");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 20;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        formularioContainer.add(jrb12, gridBagConstraints);

        jrb14.setLabel("14");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 21;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 23;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        formularioContainer.add(jrb14, gridBagConstraints);

        jrb16.setLabel("16");
        jrb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb16ActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 44;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        formularioContainer.add(jrb16, gridBagConstraints);

        jrb18.setLabel("18");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 45;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 12, 0, 0);
        formularioContainer.add(jrb18, gridBagConstraints);

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton1.setText("Enviar");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 44;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(18, 24, 6, 0);
        formularioContainer.add(jButton1, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(formularioContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(10, 10, 10)
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(formularioContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(46, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb16ActionPerformed

    private void jrbLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbLivreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbLivreActionPerformed

    private void tfEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEstudioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel formularioContainer;
    private javax.swing.JButton jButton1;
    private javax.swing.JRadioButton jrb10;
    private javax.swing.JRadioButton jrb12;
    private javax.swing.JRadioButton jrb14;
    private javax.swing.JRadioButton jrb16;
    private javax.swing.JRadioButton jrb18;
    private javax.swing.JRadioButton jrbLivre;
    private javax.swing.JLabel lClassificacao;
    private javax.swing.JLabel lDistribuidora;
    private javax.swing.JLabel lDuraco;
    private javax.swing.JLabel lEstudio;
    private javax.swing.JLabel lFormato;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPreco;
    private javax.swing.JLabel lTipoMidia;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JTextField tfDistribuidora;
    private javax.swing.JTextField tfDuracao;
    private javax.swing.JTextField tfEstudio;
    private javax.swing.JTextField tfFormato;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPreco;
    private javax.swing.JTextField tfTipoMidia;
    // End of variables declaration//GEN-END:variables
}
