/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontEnd.formularios;

import java.awt.event.ActionEvent;
import java.util.Enumeration;

import javax.swing.AbstractButton;
import javax.swing.ButtonGroup;
import javax.swing.ButtonModel;
import javax.swing.JOptionPane;

import static ferramentas.VerificarDados.verifTel;

import dados.Game;

/**
 *
 * @author gbert
 */
public class FormularioJogo extends javax.swing.JPanel {

    /**
     * Creates new form FomularioJogo
     */
    public FormularioJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fomularioContainer = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lDesenvolvedora = new javax.swing.JLabel();
        tfDesenvolvedora = new javax.swing.JTextField();
        lPublicadora = new javax.swing.JLabel();
        tfPublicadora = new javax.swing.JTextField();
        lPlataforma = new javax.swing.JLabel();
        lEstoque = new javax.swing.JLabel();
        lClassificacao = new javax.swing.JLabel();
        botaoEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfPreco = new javax.swing.JTextField();
        tfEstoque = new javax.swing.JTextField();
        tfPlataforma = new javax.swing.JComboBox<>();
        tfClassificacao = new javax.swing.JComboBox<>();

        setMaximumSize(new java.awt.Dimension(500, 32767));
        setMinimumSize(new java.awt.Dimension(500, 600));
        setPreferredSize(new java.awt.Dimension(500, 600));

        fomularioContainer.setBackground(new java.awt.Color(204, 204, 204));
        fomularioContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        fomularioContainer.setLayout(new java.awt.GridBagLayout());

        lNome.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lNome.setText("Nome do jogo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 11, 0, 0);
        fomularioContainer.add(lNome, gridBagConstraints);

        tfNome.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfNome.setToolTipText("Digite o nome do jogo");
        tfNome.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 418;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 11, 0, 11);
        fomularioContainer.add(tfNome, gridBagConstraints);

        lDesenvolvedora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lDesenvolvedora.setText("Desenvolvedora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 0);
        fomularioContainer.add(lDesenvolvedora, gridBagConstraints);

        tfDesenvolvedora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfDesenvolvedora.setToolTipText("Digite a desenvolvedora do jogo");
        tfDesenvolvedora.setPreferredSize(new java.awt.Dimension(400, 27));
        tfDesenvolvedora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDesenvolvedoraActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 418;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 11);
        fomularioContainer.add(tfDesenvolvedora, gridBagConstraints);

        lPublicadora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lPublicadora.setText("Publicadora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 0);
        fomularioContainer.add(lPublicadora, gridBagConstraints);

        tfPublicadora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfPublicadora.setToolTipText("Digite o nome da publicadora");
        tfPublicadora.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 418;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 11);
        fomularioContainer.add(tfPublicadora, gridBagConstraints);

        lPlataforma.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lPlataforma.setText("Plataforma");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 0, 0);
        fomularioContainer.add(lPlataforma, gridBagConstraints);

        lEstoque.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lEstoque.setText("Estoque");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 0, 0);
        fomularioContainer.add(lEstoque, gridBagConstraints);

        lClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lClassificacao.setText("Classificação indicativa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = -6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 0);
        fomularioContainer.add(lClassificacao, gridBagConstraints);

        botaoEnviar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoEnviar.setText("Enviar");
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 410;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(66, 11, 11, 11);
        fomularioContainer.add(botaoEnviar, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Preço");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 0, 0);
        fomularioContainer.add(jLabel1, gridBagConstraints);

        tfPreco.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfPreco.setToolTipText("preço");
        tfPreco.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 418;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 11);
        fomularioContainer.add(tfPreco, gridBagConstraints);

        tfEstoque.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfEstoque.setToolTipText("Digite a quantidade do item no estoque");
        tfEstoque.setPreferredSize(new java.awt.Dimension(400, 27));
        tfEstoque.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEstoqueActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 418;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 11);
        fomularioContainer.add(tfEstoque, gridBagConstraints);

        tfPlataforma.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfPlataforma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Console", "PC" }));
        tfPlataforma.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 389;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 11, 0, 11);
        fomularioContainer.add(tfPlataforma, gridBagConstraints);

        tfClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfClassificacao.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Livre", "10", "12", "14", "16", "18" }));
        tfClassificacao.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 410;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 0, 11);
        fomularioContainer.add(tfClassificacao, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fomularioContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 529, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fomularioContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    protected void tfDesenvolvedoraActionPerformed(ActionEvent evt) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'tfDesenvolvedoraActionPerformed'");
    }

    protected void tfEstoqueActionPerformed(ActionEvent evt) {
        // TODO Auto-generated method stub
        throw new UnsupportedOperationException("Unimplemented method 'tfEstoqueActionPerformed'");
    }

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoEnviarActionPerformed
        // Pega os dados dos campos
        String nome = tfNome.getText();
        String desenvolvedora = tfDesenvolvedora.getText();
        String plataforma = tfPlataforma.getSelectedItem().toString();
        String publicadora = tfPublicadora.getText();
        int preco = Integer.parseInt(tfPreco.getText());
        String classificacao = tfClassificacao.getSelectedItem().toString();
        int estoque = Integer.parseInt(tfEstoque.getText());

        // Verifica se os campos estão vazios
        if (nome.isEmpty() || desenvolvedora.isEmpty() || plataforma.isEmpty()
                || publicadora.isEmpty() || classificacao == null) {
            JOptionPane.showMessageDialog(fomularioContainer, "Por favor, preencha todos os campos.");
            return;
        }

        // Verifica se o preço é um número válido
        if (preco < 0) {
            JOptionPane.showMessageDialog(fomularioContainer, "Por favor, insira um preço válido.");
            return;
        }

        //verifica se o estoque é um número válido
        if (estoque < 0) {
            JOptionPane.showMessageDialog(fomularioContainer, "Por favor, insira um estoque válido.");
            return;
        }
        
        // Cria o objeto Jogo
        Game jogo = new Game(
                nome,
                ferramentas.GeradorID.gerarID(), // código id automatico
                classificacao,
                publicadora,
                desenvolvedora,
                plataforma,
                false, // está alugado
                0, // alugueis
                1, // estoque (pode ser inicializado com 1 cópia)
                preco);

        // Salva o jogo no banco de dados
        ferramentas.CrudProduto.criarProduto(jogo, "jogos");

        // Limpa os campos do formulário
        tfNome.setText("");
        tfDesenvolvedora.setText("");
        tfPublicadora.setText("");
        tfPreco.setText("");
        tfEstoque.setText("");
        tfPlataforma.setSelectedIndex(0);
        tfClassificacao.setSelectedIndex(0);
    }// GEN-LAST:event_botaoEnviarActionPerformed

    private String getClassificacaoSelecionada(ButtonGroup g) {
        for (Enumeration<AbstractButton> buttons = g.getElements(); buttons.hasMoreElements();) {
            AbstractButton button = buttons.nextElement();

            if (button.isSelected()) {
                return button.getText();
            }
        }
        return null;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JPanel fomularioContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lClassificacao;
    private javax.swing.JLabel lDesenvolvedora;
    private javax.swing.JLabel lEstoque;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPlataforma;
    private javax.swing.JLabel lPublicadora;
    private javax.swing.JComboBox<String> tfClassificacao;
    private javax.swing.JTextField tfDesenvolvedora;
    private javax.swing.JTextField tfEstoque;
    private javax.swing.JTextField tfNome;
    private javax.swing.JComboBox<String> tfPlataforma;
    private javax.swing.JTextField tfPreco;
    private javax.swing.JTextField tfPublicadora;
    // End of variables declaration//GEN-END:variables
}
