/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontEnd.formularios;

/**
 *
 * @author gbert
 */
public class FormularioJogo extends javax.swing.JPanel {

    /**
     * Creates new form FomularioJogo
     */
    public FormularioJogo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        grupoBotoesClassificacao = new javax.swing.ButtonGroup();
        lTitulo = new javax.swing.JLabel();
        fomularioContainer = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lDesenvolvedora = new javax.swing.JLabel();
        tfDesenvolvedora = new javax.swing.JTextField();
        lPublicadora = new javax.swing.JLabel();
        tfPublicadora = new javax.swing.JTextField();
        lPlataforma = new javax.swing.JLabel();
        tfPlataforma = new javax.swing.JTextField();
        lClassificacao = new javax.swing.JLabel();
        jrbLivre = new javax.swing.JRadioButton();
        jrb12 = new javax.swing.JRadioButton();
        jrb16 = new javax.swing.JRadioButton();
        jrb10 = new javax.swing.JRadioButton();
        jrb14 = new javax.swing.JRadioButton();
        jrb18 = new javax.swing.JRadioButton();
        botaoEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();

        setMinimumSize(new java.awt.Dimension(500, 600));
        setPreferredSize(new java.awt.Dimension(500, 600));

        lTitulo.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        lTitulo.setText("Fomulario cadastro de jogos");

        fomularioContainer.setBackground(new java.awt.Color(204, 204, 204));
        fomularioContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));

        lNome.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lNome.setText("Nome do jogo");

        tfNome.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfNome.setToolTipText("Digite o nome do jogo");

        lDesenvolvedora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lDesenvolvedora.setText("Desenvolvedora");

        tfDesenvolvedora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfDesenvolvedora.setToolTipText("Digite a desenvolvedora do jogo");
        tfDesenvolvedora.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDesenvolvedoraActionPerformed(evt);
            }
        });

        lPublicadora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lPublicadora.setText("Publicadora");

        tfPublicadora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfPublicadora.setToolTipText("Digite o nome da publicadora");

        lPlataforma.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lPlataforma.setText("Plataforma");

        tfPlataforma.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfPlataforma.setToolTipText("Digite o nome da plataforma do jogo");

        lClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lClassificacao.setText("Classificação indicativa");

        grupoBotoesClassificacao.add(jrbLivre);
        jrbLivre.setLabel("livre");
        jrbLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbLivreActionPerformed(evt);
            }
        });

        grupoBotoesClassificacao.add(jrb12);
        jrb12.setLabel("12");

        grupoBotoesClassificacao.add(jrb16);
        jrb16.setLabel("16");
        jrb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb16ActionPerformed(evt);
            }
        });

        grupoBotoesClassificacao.add(jrb10);
        jrb10.setLabel("10");

        grupoBotoesClassificacao.add(jrb14);
        jrb14.setLabel("14");

        grupoBotoesClassificacao.add(jrb18);
        jrb18.setLabel("18");

        botaoEnviar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoEnviar.setText("Enviar");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Preço");

        jTextField1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jTextField1.setToolTipText("preço");

        javax.swing.GroupLayout fomularioContainerLayout = new javax.swing.GroupLayout(fomularioContainer);
        fomularioContainer.setLayout(fomularioContainerLayout);
        fomularioContainerLayout.setHorizontalGroup(
            fomularioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fomularioContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(fomularioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNome)
                    .addComponent(tfDesenvolvedora)
                    .addComponent(tfPublicadora)
                    .addComponent(tfPlataforma, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                    .addGroup(fomularioContainerLayout.createSequentialGroup()
                        .addGroup(fomularioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(fomularioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addComponent(botaoEnviar)
                                .addGroup(fomularioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lNome)
                                    .addComponent(lDesenvolvedora)
                                    .addComponent(lPublicadora)
                                    .addComponent(lPlataforma)
                                    .addComponent(lClassificacao)
                                    .addGroup(fomularioContainerLayout.createSequentialGroup()
                                        .addComponent(jrbLivre)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jrb10)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jrb12)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jrb14)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jrb16)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jrb18))))
                            .addComponent(jLabel1))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTextField1))
                .addContainerGap())
        );
        fomularioContainerLayout.setVerticalGroup(
            fomularioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(fomularioContainerLayout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addComponent(lNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lDesenvolvedora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDesenvolvedora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lPublicadora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPublicadora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lPlataforma)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPlataforma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 32, Short.MAX_VALUE)
                .addComponent(lClassificacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(fomularioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbLivre)
                    .addComponent(jrb12)
                    .addComponent(jrb16)
                    .addComponent(jrb10)
                    .addComponent(jrb14)
                    .addComponent(jrb18))
                .addGap(18, 18, 18)
                .addComponent(botaoEnviar)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lTitulo)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(fomularioContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(fomularioContainer, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void tfDesenvolvedoraActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDesenvolvedoraActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDesenvolvedoraActionPerformed

    private void jrbLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbLivreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbLivreActionPerformed

    private void jrb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb16ActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JPanel fomularioContainer;
    private javax.swing.ButtonGroup grupoBotoesClassificacao;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JRadioButton jrb10;
    private javax.swing.JRadioButton jrb12;
    private javax.swing.JRadioButton jrb14;
    private javax.swing.JRadioButton jrb16;
    private javax.swing.JRadioButton jrb18;
    private javax.swing.JRadioButton jrbLivre;
    private javax.swing.JLabel lClassificacao;
    private javax.swing.JLabel lDesenvolvedora;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPlataforma;
    private javax.swing.JLabel lPublicadora;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JTextField tfDesenvolvedora;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPlataforma;
    private javax.swing.JTextField tfPublicadora;
    // End of variables declaration//GEN-END:variables
}
