/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEnd.formularios;

import dados.Game;
import static ferramentas.CrudProduto.editarProduto;

import javax.swing.JOptionPane;

/**
 *
 * @author gbert
 */
public class FormularioEditarJogo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(FormularioEditarJogo.class.getName());

    /**
     * Creates new form FormularioEditarJogo
     */
    Game game;
    private Runnable callback;

    public FormularioEditarJogo() {
        initComponents();
    }

    public FormularioEditarJogo(Game game, Runnable callback) {
        initComponents();
        this.game = game;
        this.callback = callback;
        tfNome.setText(game.getNome());
        tfDesenvolvedora.setText(game.getDesenvolvedor());
        tfPublicadora.setText(game.getPublicadora());
        tfPreco.setText(String.valueOf(game.getPreco()));
        tfEstoque.setText(String.valueOf(game.getEstoque()));
        tfPlataforma.setSelectedItem(game.getPlataforma());
        tfClassificacao.setSelectedItem(game.getClassInd());
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        fomularioContainer = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lDesenvolvedora = new javax.swing.JLabel();
        tfDesenvolvedora = new javax.swing.JTextField();
        lPublicadora = new javax.swing.JLabel();
        tfPublicadora = new javax.swing.JTextField();
        lPlataforma = new javax.swing.JLabel();
        lEstoque = new javax.swing.JLabel();
        lClassificacao = new javax.swing.JLabel();
        botaoEnviar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        tfPreco = new javax.swing.JTextField();
        tfEstoque = new javax.swing.JTextField();
        tfPlataforma = new javax.swing.JComboBox<>();
        tfClassificacao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        fomularioContainer.setBackground(new java.awt.Color(204, 204, 204));
        fomularioContainer.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        fomularioContainer.setLayout(new java.awt.GridBagLayout());

        lNome.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lNome.setText("Nome do jogo");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(36, 11, 0, 0);
        fomularioContainer.add(lNome, gridBagConstraints);

        tfNome.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfNome.setToolTipText("Digite o nome do jogo");
        tfNome.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 418;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 11, 0, 11);
        fomularioContainer.add(tfNome, gridBagConstraints);

        lDesenvolvedora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lDesenvolvedora.setText("Desenvolvedora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 0);
        fomularioContainer.add(lDesenvolvedora, gridBagConstraints);

        tfDesenvolvedora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfDesenvolvedora.setToolTipText("Digite a desenvolvedora do jogo");
        tfDesenvolvedora.setPreferredSize(new java.awt.Dimension(400, 27));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 418;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 11);
        fomularioContainer.add(tfDesenvolvedora, gridBagConstraints);

        lPublicadora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lPublicadora.setText("Publicadora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 0);
        fomularioContainer.add(lPublicadora, gridBagConstraints);

        tfPublicadora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfPublicadora.setToolTipText("Digite o nome da publicadora");
        tfPublicadora.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 418;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 11);
        fomularioContainer.add(tfPublicadora, gridBagConstraints);

        lPlataforma.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lPlataforma.setText("Plataforma");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 0, 0);
        fomularioContainer.add(lPlataforma, gridBagConstraints);

        lEstoque.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lEstoque.setText("Estoque");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 0, 0);
        fomularioContainer.add(lEstoque, gridBagConstraints);

        lClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lClassificacao.setText("Classificação indicativa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.ipadx = -6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 0);
        fomularioContainer.add(lClassificacao, gridBagConstraints);

        botaoEnviar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoEnviar.setText("Enviar");
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 410;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(66, 11, 11, 11);
        fomularioContainer.add(botaoEnviar, gridBagConstraints);

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Preço");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 0, 0);
        fomularioContainer.add(jLabel1, gridBagConstraints);

        tfPreco.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfPreco.setToolTipText("preço");
        tfPreco.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 418;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 11);
        fomularioContainer.add(tfPreco, gridBagConstraints);

        tfEstoque.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfEstoque.setToolTipText("Digite a quantidade do item no estoque");
        tfEstoque.setPreferredSize(new java.awt.Dimension(400, 27));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 418;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 11, 0, 11);
        fomularioContainer.add(tfEstoque, gridBagConstraints);

        tfPlataforma.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfPlataforma.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Console", "PC" }));
        tfPlataforma.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 389;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 11, 0, 11);
        fomularioContainer.add(tfPlataforma, gridBagConstraints);

        tfClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfClassificacao.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Livre", "10", "12", "14", "16", "18" }));
        tfClassificacao.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.ipadx = 410;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 11, 0, 11);
        fomularioContainer.add(tfClassificacao, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(fomularioContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 514,
                                        Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(fomularioContainer, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoEnviarActionPerformed
        // Pega os dados dos campos
        this.game.setNome(tfNome.getText());
        this.game.setDesenvolvedor(tfDesenvolvedora.getText());
        this.game.setPublicadora(tfPublicadora.getText());
        this.game.setPreco(Integer.parseInt(tfPreco.getText()));
        this.game.setEstoque(Integer.parseInt(tfEstoque.getText()));
        this.game.setPlataforma((String) tfPlataforma.getSelectedItem());
        this.game.setClassInd((String) tfClassificacao.getSelectedItem());
        // Salva o usuario
        editarProduto(this.game.getCodigo(), "jogos", this.game);
        JOptionPane.showMessageDialog(fomularioContainer, "jogo " + this.game.getNome() + " editado atualize os dados");
        if (callback != null) {
            callback.run(); // avisa a tela para atualizar
        }

        this.dispose(); // fecha a tela de edição
    }// GEN-LAST:event_botaoEnviarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormularioEditarJogo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JPanel fomularioContainer;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lClassificacao;
    private javax.swing.JLabel lDesenvolvedora;
    private javax.swing.JLabel lEstoque;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPlataforma;
    private javax.swing.JLabel lPublicadora;
    private javax.swing.JComboBox<String> tfClassificacao;
    private javax.swing.JTextField tfDesenvolvedora;
    private javax.swing.JTextField tfEstoque;
    private javax.swing.JTextField tfNome;
    private javax.swing.JComboBox<String> tfPlataforma;
    private javax.swing.JTextField tfPreco;
    private javax.swing.JTextField tfPublicadora;
    // End of variables declaration//GEN-END:variables
}
