//Autores
//PEDRO LEONARDO S. DA S. DE O. PERES 
//LORENZO DE OLIVEIRA E SILVA 
//GABRIEL EVANGELISTA BERTOLINO DOS SANTOS


/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEnd.formularios;

import dados.Produto;
import dados.Venda;
import static ferramentas.GeradorID.gerarID;
import static ferramentas.CrudVendas.criarVenda;
import static ferramentas.VerificarDados.estaVazio;
import static ferramentas.VerificarDados.verifTel;

import java.util.ArrayList;

import static ferramentas.CrudProduto.editarProduto;
import static ferramentas.CrudCliente.encontrarCliente;
import static ferramentas.CrudCliente.atualizarLocados;
import static ferramentas.CrudCliente.criarCliente;
import static ferramentas.CrudCliente.editarCliente;

import dados.*;
import dados.Game;
import dados.Video;

import javax.swing.JOptionPane;


/**
 *
 * @author gbert
 */
public class FormularioVenda extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(FormularioVenda.class.getName());
    Produto produto;
    /**
     * Creates new form FormularioVenda
     */
    public FormularioVenda() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    public FormularioVenda(Produto produto) {
        initComponents();
        this.produto = produto;
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTelefone = new javax.swing.JLabel();
        tfTelefone = new javax.swing.JTextField();
        botoesContainer = new javax.swing.JPanel();
        botaoEnviar = new javax.swing.JButton();
        botaoCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lTelefone.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lTelefone.setText("Telefone do Cliente");

        tfTelefone.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfTelefone.setToolTipText("Digite o telefone do Cliente");

        botoesContainer.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        botaoEnviar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoEnviar.setText("Enviar");
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });
        botoesContainer.add(botaoEnviar);

        botaoCancelar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoCancelar.setText("Cancelar");
        botaoCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoCancelarActionPerformed(evt);
            }
        });
        botoesContainer.add(botaoCancelar);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lTelefone, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(tfTelefone)
                    .addComponent(botoesContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lTelefone)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tfTelefone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 15, Short.MAX_VALUE)
                .addComponent(botoesContainer, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoEnviarActionPerformed
        String telefone = tfTelefone.getText();
        String colecao = "";
        //Verivica se produto e Game ou Video
        if(this.produto instanceof Game){
            colecao = "jogos";
        } else if (this.produto instanceof Video) {
            colecao = "videos";
        }
        //Verifica se o telefone está no formato correto
        if(estaVazio(telefone) == false){
            JOptionPane.showMessageDialog(this, "Por favor, preencha o campo telefone.", "Erro",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        if(verifTel(telefone) == false){
            JOptionPane.showMessageDialog(this, "Telefone inválido. Use o formato (XX)XXXXX-XXXX", "Erro",
                    JOptionPane.ERROR_MESSAGE);
            return;
        }
        //Cria Venda
        Venda venda = new Venda(telefone, this.produto.getCodigo(), this.produto.getPreco(), gerarID(), colecao);
        //Pega cliente
        Cliente c = ferramentas.CrudCliente.encontrarCliente(telefone);
        //Adiciona o produto na lista de locados do cliente
        c.adicionarLocado(produto);
        atualizarLocados(c);
        //Cria venda
        criarVenda(venda);
        //Modifica cliente no banco de dados
        editarCliente(c, telefone);;
        //Marca produto no banco de dados como esta alugado e diminui o estoque
        this.produto.setAlugadoStatus(true);
        this.produto.setAlugueis(this.produto.getAlugueis() + 1);
        this.produto.setEstoque(this.produto.getEstoque() - 1);
        editarProduto(this.produto.getCodigo(), colecao, this.produto);
        this.dispose();
    }//GEN-LAST:event_botaoEnviarActionPerformed

    private void botaoCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoCancelarActionPerformed
        this.dispose();
    }//GEN-LAST:event_botaoCancelarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormularioVenda().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoCancelar;
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JPanel botoesContainer;
    private javax.swing.JLabel lTelefone;
    private javax.swing.JTextField tfTelefone;
    // End of variables declaration//GEN-END:variables
}
