/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontEnd.formularios;

/**
 *
 * @author gbert
 */
public class FormularioVideo extends javax.swing.JPanel {

    /**
     * Creates new form FomularioFilme
     */
    public FormularioVideo() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lTitulo = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        formularioContainer = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lEstudio = new javax.swing.JLabel();
        tfEstudio = new javax.swing.JTextField();
        lDistribuidora = new javax.swing.JLabel();
        tfDistribuidora = new javax.swing.JTextField();
        lFormato = new javax.swing.JLabel();
        tfFormato = new javax.swing.JTextField();
        lTipoMidia = new javax.swing.JLabel();
        tfTipoMidia = new javax.swing.JTextField();
        lDuraco = new javax.swing.JLabel();
        tfDuracao = new javax.swing.JTextField();
        lPreco = new javax.swing.JLabel();
        tfPreco = new javax.swing.JTextField();
        lClassificacao = new javax.swing.JLabel();
        jrbLivre = new javax.swing.JRadioButton();
        jrb10 = new javax.swing.JRadioButton();
        jrb12 = new javax.swing.JRadioButton();
        jrb14 = new javax.swing.JRadioButton();
        jrb16 = new javax.swing.JRadioButton();
        jrb18 = new javax.swing.JRadioButton();
        jButton1 = new javax.swing.JButton();

        setMinimumSize(new java.awt.Dimension(500, 650));
        setPreferredSize(new java.awt.Dimension(500, 650));

        lTitulo.setFont(new java.awt.Font("Segoe UI", 0, 25)); // NOI18N
        lTitulo.setText("Formulario Cadastro de video");

        formularioContainer.setBackground(new java.awt.Color(204, 204, 204));

        lNome.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lNome.setText("Nome");

        tfNome.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfNome.setToolTipText("Digite o nome do jogo");

        lEstudio.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lEstudio.setText("Estudio");

        tfEstudio.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfEstudio.setToolTipText("Digite a desenvolvedora do jogo");
        tfEstudio.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfEstudioActionPerformed(evt);
            }
        });

        lDistribuidora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lDistribuidora.setText("Distribuidora");

        tfDistribuidora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfDistribuidora.setToolTipText("Digite o nome da publicadora");

        lFormato.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lFormato.setText("Formato");

        tfFormato.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfFormato.setToolTipText("Digite o nome da plataforma do jogo");

        lTipoMidia.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lTipoMidia.setText("Tipo de midia");

        tfTipoMidia.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfTipoMidia.setToolTipText("preço");

        lDuraco.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lDuraco.setText("Duração");

        tfDuracao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfDuracao.setToolTipText("preço");

        lPreco.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lPreco.setText("Preço");

        tfPreco.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfPreco.setToolTipText("preço");

        lClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lClassificacao.setText("Classificação indicativa");

        jrbLivre.setLabel("livre");
        jrbLivre.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrbLivreActionPerformed(evt);
            }
        });

        jrb10.setLabel("10");

        jrb12.setLabel("12");

        jrb14.setLabel("14");

        jrb16.setLabel("16");
        jrb16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jrb16ActionPerformed(evt);
            }
        });

        jrb18.setLabel("18");

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jButton1.setText("Enviar");

        javax.swing.GroupLayout formularioContainerLayout = new javax.swing.GroupLayout(formularioContainer);
        formularioContainer.setLayout(formularioContainerLayout);
        formularioContainerLayout.setHorizontalGroup(
            formularioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioContainerLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(formularioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tfNome)
                    .addComponent(tfEstudio)
                    .addComponent(tfDistribuidora)
                    .addComponent(tfFormato)
                    .addComponent(tfTipoMidia)
                    .addComponent(tfDuracao)
                    .addComponent(tfPreco)
                    .addGroup(formularioContainerLayout.createSequentialGroup()
                        .addGroup(formularioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton1)
                            .addGroup(formularioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(lNome)
                                .addComponent(lEstudio)
                                .addComponent(lDistribuidora)
                                .addComponent(lFormato)
                                .addComponent(lTipoMidia)
                                .addComponent(lDuraco)
                                .addComponent(lPreco)
                                .addComponent(lClassificacao)
                                .addGroup(formularioContainerLayout.createSequentialGroup()
                                    .addComponent(jrbLivre)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jrb10)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jrb12)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jrb14)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jrb16)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(jrb18))))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        formularioContainerLayout.setVerticalGroup(
            formularioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(formularioContainerLayout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(lNome)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lEstudio)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfEstudio, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lDistribuidora)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDistribuidora, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lFormato)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfFormato, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lTipoMidia)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfTipoMidia, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lDuraco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfDuracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lPreco)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tfPreco, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lClassificacao)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(formularioContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jrbLivre)
                    .addComponent(jrb12)
                    .addComponent(jrb16)
                    .addComponent(jrb10)
                    .addComponent(jrb14)
                    .addComponent(jrb18))
                .addGap(18, 18, 18)
                .addComponent(jButton1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jScrollPane2.setViewportView(formularioContainer);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addComponent(lTitulo)
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(106, 106, 106)
                .addComponent(lTitulo)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 603, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jrb16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrb16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrb16ActionPerformed

    private void jrbLivreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jrbLivreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jrbLivreActionPerformed

    private void tfEstudioActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfEstudioActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfEstudioActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel formularioContainer;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JRadioButton jrb10;
    private javax.swing.JRadioButton jrb12;
    private javax.swing.JRadioButton jrb14;
    private javax.swing.JRadioButton jrb16;
    private javax.swing.JRadioButton jrb18;
    private javax.swing.JRadioButton jrbLivre;
    private javax.swing.JLabel lClassificacao;
    private javax.swing.JLabel lDistribuidora;
    private javax.swing.JLabel lDuraco;
    private javax.swing.JLabel lEstudio;
    private javax.swing.JLabel lFormato;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPreco;
    private javax.swing.JLabel lTipoMidia;
    private javax.swing.JLabel lTitulo;
    private javax.swing.JTextField tfDistribuidora;
    private javax.swing.JTextField tfDuracao;
    private javax.swing.JTextField tfEstudio;
    private javax.swing.JTextField tfFormato;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPreco;
    private javax.swing.JTextField tfTipoMidia;
    // End of variables declaration//GEN-END:variables
}
