/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEnd.formularios;

import dados.Video;
import static ferramentas.CrudProduto.editarProduto;

import javax.swing.JOptionPane;

/**
 *
 * @author gbert
 */
public class FormularioEditarVideo extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(FormularioEditarVideo.class.getName());

    /**
     * Creates new form FormularioEditarVideo
     */
    Video video;
    private Runnable callback;

    public FormularioEditarVideo() {
        initComponents();
    }

    public FormularioEditarVideo(Video video, Runnable callback) {
        initComponents();
        this.video = video;
        this.callback = callback;
        tfNome.setText(video.getNome());
        tfEstudio.setText(video.getEstudio());
        tfDistribuidora.setText(video.getDistribuidora());
        tfDuracao.setText(String.valueOf(video.getDuracao()));
        tfPreco.setText(String.valueOf(video.getPreco()));
        tfClassificacao.setSelectedItem(video.getClassInd());
        tfFormato.setSelectedItem(video.getFormato());
        tfTipoMidia.setSelectedItem(video.getTipoMidia());
        tfEstoque.setText(String.valueOf(video.getEstoque()));
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {
        java.awt.GridBagConstraints gridBagConstraints;

        formularioContainer = new javax.swing.JPanel();
        lNome = new javax.swing.JLabel();
        tfNome = new javax.swing.JTextField();
        lEstudio = new javax.swing.JLabel();
        tfEstudio = new javax.swing.JTextField();
        lDistribuidora = new javax.swing.JLabel();
        tfDistribuidora = new javax.swing.JTextField();
        lFormato = new javax.swing.JLabel();
        lTipoMidia = new javax.swing.JLabel();
        lDuraco = new javax.swing.JLabel();
        tfDuracao = new javax.swing.JTextField();
        lPreco = new javax.swing.JLabel();
        tfPreco = new javax.swing.JTextField();
        lClassificacao = new javax.swing.JLabel();
        botaoEnviar = new javax.swing.JButton();
        tfEstoque = new javax.swing.JTextField();
        lEstoque = new javax.swing.JLabel();
        tfFormato = new javax.swing.JComboBox<>();
        tfTipoMidia = new javax.swing.JComboBox<>();
        tfClassificacao = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        formularioContainer.setBackground(new java.awt.Color(204, 204, 204));
        formularioContainer.setMaximumSize(new java.awt.Dimension(500, 32767));
        formularioContainer.setLayout(new java.awt.GridBagLayout());

        lNome.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lNome.setText("Nome");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 0;
        gridBagConstraints.gridwidth = 2;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(10, 6, 0, 0);
        formularioContainer.add(lNome, gridBagConstraints);

        tfNome.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfNome.setToolTipText("Digite o nome do Filme");
        tfNome.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 1;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 412;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        formularioContainer.add(tfNome, gridBagConstraints);

        lEstudio.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lEstudio.setText("Estudio");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 2;
        gridBagConstraints.gridwidth = 3;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        formularioContainer.add(lEstudio, gridBagConstraints);

        tfEstudio.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfEstudio.setToolTipText("Digite o nome do estudio");
        tfEstudio.setPreferredSize(new java.awt.Dimension(400, 27));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 3;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 412;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        formularioContainer.add(tfEstudio, gridBagConstraints);

        lDistribuidora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lDistribuidora.setText("Distribuidora");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 4;
        gridBagConstraints.gridwidth = 7;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        formularioContainer.add(lDistribuidora, gridBagConstraints);

        tfDistribuidora.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfDistribuidora.setToolTipText("Digite o nome da distribuidora");
        tfDistribuidora.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 5;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 412;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        formularioContainer.add(tfDistribuidora, gridBagConstraints);

        lFormato.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lFormato.setText("Formato");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 12;
        gridBagConstraints.gridwidth = 5;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        formularioContainer.add(lFormato, gridBagConstraints);

        lTipoMidia.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lTipoMidia.setText("Tipo de midia");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 14;
        gridBagConstraints.gridwidth = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        formularioContainer.add(lTipoMidia, gridBagConstraints);

        lDuraco.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lDuraco.setText("Duração");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 6;
        gridBagConstraints.gridwidth = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        formularioContainer.add(lDuraco, gridBagConstraints);

        tfDuracao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfDuracao.setToolTipText("digite a duração");
        tfDuracao.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 7;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 412;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        formularioContainer.add(tfDuracao, gridBagConstraints);

        lPreco.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lPreco.setText("Preço");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 8;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        formularioContainer.add(lPreco, gridBagConstraints);

        tfPreco.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfPreco.setToolTipText("preço");
        tfPreco.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 9;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 412;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        formularioContainer.add(tfPreco, gridBagConstraints);

        lClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lClassificacao.setText("Classificação indicativa");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 16;
        gridBagConstraints.gridwidth = 9;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 0);
        formularioContainer.add(lClassificacao, gridBagConstraints);

        botaoEnviar.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoEnviar.setText("Enviar");
        botaoEnviar.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        botaoEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEnviarActionPerformed(evt);
            }
        });
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 18;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 404;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 6, 6);
        formularioContainer.add(botaoEnviar, gridBagConstraints);

        tfEstoque.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfEstoque.setToolTipText("Digite a quantidade do item no estoque");
        tfEstoque.setPreferredSize(new java.awt.Dimension(400, 27));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 11;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 412;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 6);
        formularioContainer.add(tfEstoque, gridBagConstraints);

        lEstoque.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lEstoque.setText("Estoque");
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 10;
        gridBagConstraints.gridwidth = 4;
        gridBagConstraints.ipady = 6;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(6, 6, 0, 0);
        formularioContainer.add(lEstoque, gridBagConstraints);

        tfFormato.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfFormato.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "DVD", "Blu-Ray", "CD" }));
        tfFormato.setToolTipText("Escolha o formato ");
        tfFormato.setPreferredSize(new java.awt.Dimension(400, 27));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 13;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 385;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(5, 6, 0, 6);
        formularioContainer.add(tfFormato, gridBagConstraints);

        tfTipoMidia.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfTipoMidia.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Filme", "Série", "Coletânea" }));
        tfTipoMidia.setToolTipText("Escolha o tipo de midia");
        tfTipoMidia.setPreferredSize(new java.awt.Dimension(400, 27));
        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 15;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 369;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 6);
        formularioContainer.add(tfTipoMidia, gridBagConstraints);

        tfClassificacao.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        tfClassificacao.setModel(
                new javax.swing.DefaultComboBoxModel<>(new String[] { "Livre", "10", "12", "14", "16", "18" }));
        tfClassificacao.setToolTipText("Escolha a classificação indicativa");
        tfClassificacao.setPreferredSize(new java.awt.Dimension(400, 27));

        gridBagConstraints = new java.awt.GridBagConstraints();
        gridBagConstraints.gridx = 0;
        gridBagConstraints.gridy = 17;
        gridBagConstraints.gridwidth = 10;
        gridBagConstraints.ipadx = 404;
        gridBagConstraints.anchor = java.awt.GridBagConstraints.NORTHWEST;
        gridBagConstraints.insets = new java.awt.Insets(12, 6, 0, 6);
        formularioContainer.add(tfClassificacao, gridBagConstraints);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(formularioContainer, javax.swing.GroupLayout.DEFAULT_SIZE, 488,
                                        Short.MAX_VALUE)
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(formularioContainer, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEnviarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoEnviarActionPerformed
        this.video.setNome(tfNome.getText());
        this.video.setEstudio(tfEstudio.getText());
        this.video.setDistribuidora(tfDistribuidora.getText());
        this.video.setTipoMidia(tfTipoMidia.getSelectedItem().toString());
        this.video.setClassInd(tfClassificacao.getSelectedItem().toString());
        this.video.setFormato(tfFormato.getSelectedItem().toString());
        this.video.setDuracao(parseInt(tfDuracao.getText()));
        this.video.setEstoque(parseInt(tfEstoque.getText()));
        this.video.setPreco(parseInt(tfPreco.getText()));

        editarProduto(this.video.getCodigo(), "videos", this.video);
        JOptionPane.showMessageDialog(formularioContainer,
                "Video " + this.video.getNome() + " editado");
        if (callback != null) {
            callback.run(); // avisa a tela para atualizar
        }

        this.dispose(); // fecha a tela de edição

    }// GEN-LAST:event_botaoEnviarActionPerformed

    private int parseInt(String text) {
        if (text == null || text.isEmpty()) {
            return 0; // or any default value you prefer
        }
        return Integer.parseInt(text);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new FormularioEditarVideo().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoEnviar;
    private javax.swing.JPanel formularioContainer;
    private javax.swing.JLabel lClassificacao;
    private javax.swing.JLabel lDistribuidora;
    private javax.swing.JLabel lDuraco;
    private javax.swing.JLabel lEstoque;
    private javax.swing.JLabel lEstudio;
    private javax.swing.JLabel lFormato;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPreco;
    private javax.swing.JLabel lTipoMidia;
    private javax.swing.JComboBox<String> tfClassificacao;
    private javax.swing.JTextField tfDistribuidora;
    private javax.swing.JTextField tfDuracao;
    private javax.swing.JTextField tfEstoque;
    private javax.swing.JTextField tfEstudio;
    private javax.swing.JComboBox<String> tfFormato;
    private javax.swing.JTextField tfNome;
    private javax.swing.JTextField tfPreco;
    private javax.swing.JComboBox<String> tfTipoMidia;
    // End of variables declaration//GEN-END:variables
}
