/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontEnd.telas;

import frontEnd.formularios.FormularioJogo;
import frontEnd.formularios.FormularioVideo;
import java.awt.CardLayout;

/**
 *
 * @author gbert
 */
public class CadastrarProdutos extends javax.swing.JPanel {

    /**
     * Creates new form CadastrarProdutos
     */
    FormularioVideo formularioVideo;
    FormularioJogo formularioJogo;
    public CadastrarProdutos() {
        initComponents();
        formularioVideo = new FormularioVideo();
        formularioJogo = new FormularioJogo();
        jFormulario.add(formularioVideo, "Video");
        jFormulario.add(formularioJogo, "Jogo");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jBotoes = new javax.swing.JPanel();
        botaoVideo = new javax.swing.JButton();
        botaoJogo = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jFormulario = new javax.swing.JPanel();

        setPreferredSize(new java.awt.Dimension(700, 700));

        jBotoes.setBackground(new java.awt.Color(204, 204, 204));
        jBotoes.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        jBotoes.setLayout(new java.awt.GridLayout(1, 0, 10, 0));

        botaoVideo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        botaoVideo.setText("Video");
        botaoVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVideoActionPerformed(evt);
            }
        });
        jBotoes.add(botaoVideo);

        botaoJogo.setFont(new java.awt.Font("Segoe UI", 0, 20)); // NOI18N
        botaoJogo.setText("Jogo");
        botaoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoJogoActionPerformed(evt);
            }
        });
        jBotoes.add(botaoJogo);

        jFormulario.setLayout(new java.awt.CardLayout());
        jScrollPane1.setViewportView(jFormulario);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
            .addComponent(jScrollPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 650, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoJogoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoJogoActionPerformed
        CardLayout cl = (CardLayout) jFormulario.getLayout();
        cl.show(jFormulario, "Jogo");
    }//GEN-LAST:event_botaoJogoActionPerformed

    private void botaoVideoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoVideoActionPerformed
        CardLayout cl = (CardLayout) jFormulario.getLayout();
        cl.show(jFormulario, "Video");
    }//GEN-LAST:event_botaoVideoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton botaoJogo;
    private javax.swing.JButton botaoVideo;
    private javax.swing.JPanel jBotoes;
    private javax.swing.JPanel jFormulario;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
