/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEnd.telas;

import static ferramentas.CrudCliente.deletarCliente;
import static ferramentas.CrudCliente.encontrarCliente;
import static ferramentas.CrudVendas.listarVendas;

import java.time.LocalDate;
import java.time.format.DateTimeFormatter;
import java.util.List;
import java.util.zip.DataFormatException;

import javax.swing.SwingUtilities;

import dados.Cliente;
import dados.Venda;

/**
 *
 * @author gbert
 */
public class ClienteTela extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger
            .getLogger(ClienteTela.class.getName());
    Cliente cliente;
    List<Venda> vendas = listarVendas();

    /**
     * Creates new form Cliente
     */
    public ClienteTela() {
        initComponents();
    }

    public ClienteTela(dados.Cliente cliente) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.cliente = encontrarCliente(cliente.getTelefone());
        nome.setText(cliente.getNome());
        telefone.setText(cliente.getTelefone());
        endereco.setText(cliente.getEndereco());
        Multa.setText("R$ " + this.cliente.getMultaAtraso());
        atrasou.setText(cliente.getAtrasoDevol() ? "Sim" : "Não");
        configurarTabela();
        carregarLocados();
        calcularMulta();
    }

    private void calcularMulta() {
        // Calcula a multa de atraso com base nas vendas
        if (cliente == null) {
            return;
        }
        // pega a data atual e a formata
        LocalDate hoje = LocalDate.now();
        DateTimeFormatter formatter = DateTimeFormatter.ofPattern("dd/MM/yyyy");
        long totalMulta = 0;
        // percorre as vendas para calcular a multa
        for (Venda v : vendas) {
            // ignora vendas sem data de devolução
            if (v.getDataDevol() == null) {
                continue;
            }
            // calcula os dias de atraso
            LocalDate dataDevolucao = LocalDate.parse(v.getDataDevol(), formatter);
            // verifica se a venda é do cliente e se já foi devolvida
            if (v.getIdCliente().equals(cliente.getTelefone()) && !v.getFoiDevolvido() && dataDevolucao.isBefore(hoje)) {
                long diasAtraso = java.time.temporal.ChronoUnit.DAYS.between(dataDevolucao, hoje);
                // se houver atraso, calcula a multa
                if (diasAtraso > 0) {
                    totalMulta += diasAtraso * 2; // R$2 por dia
                }
            }
        }
        // atualiza a multa no cliente e na interface
        cliente.setMultaAtraso(totalMulta);
        Multa.setText("R$ " + totalMulta);
    }

    private void configurarTabela() {
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {},
                new String[] { "ID", "Nome" }) {
            @Override
            public boolean isCellEditable(int row, int column) {
                return false; // impede edição por clique/duplo-clique
            }
        });
    }

    private void carregarLocados() {
        if (cliente != null) {
            java.util.List<dados.Produto> locados = cliente.getLocados();
            javax.swing.table.DefaultTableModel model = (javax.swing.table.DefaultTableModel) jTable1.getModel();
            model.setRowCount(0); // limpa tabela

            for (dados.Produto v : locados) {
                model.addRow(new Object[] { v.getCodigo(), v.getNome() });
            }
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Informacoes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        lTelefone = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        lEndereco = new javax.swing.JLabel();
        endereco = new javax.swing.JLabel();
        lMultaAtraso = new javax.swing.JLabel();
        Multa = new javax.swing.JLabel();
        lAtrasou = new javax.swing.JLabel();
        atrasou = new javax.swing.JLabel();
        jBotoes = new javax.swing.JPanel();
        botaoExcluir = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        lLocados = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(500, 650));

        Informacoes.setLayout(new java.awt.GridLayout(11, 0, 0, 3));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Informações:");
        Informacoes.add(jLabel1);

        lNome.setText("Nome:");
        Informacoes.add(lNome);

        nome.setText("jLabel10");
        Informacoes.add(nome);

        lTelefone.setText("Telefone: ");
        Informacoes.add(lTelefone);

        telefone.setText("jLabel11");
        Informacoes.add(telefone);

        lEndereco.setText("Endereco:");
        Informacoes.add(lEndereco);

        endereco.setText("jLabel12");
        Informacoes.add(endereco);

        lMultaAtraso.setText("Multa de atraso: ");
        Informacoes.add(lMultaAtraso);

        Multa.setText("jLabel16");
        Informacoes.add(Multa);

        lAtrasou.setText("Atrasou Devolução:");
        Informacoes.add(lAtrasou);

        atrasou.setText("jLabel3");
        Informacoes.add(atrasou);

        jBotoes.setLayout(new java.awt.GridLayout(1, 0));

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
                new Object[][] {
                        { null, null },
                        { null, null }
                },
                new String[] {
                        "Title 1", "Title 2"
                }));
        jTable1.setMaximumSize(new java.awt.Dimension(150, 40));
        jTable1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTable1MouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jTable1);

        lLocados.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        lLocados.setText("Locados");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addComponent(lLocados, javax.swing.GroupLayout.PREFERRED_SIZE, 65,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(layout.createSequentialGroup()
                                                .addGroup(layout
                                                        .createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                                        .addComponent(botaoExcluir,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addComponent(Informacoes,
                                                                javax.swing.GroupLayout.Alignment.LEADING,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                        .addGroup(layout.createSequentialGroup()
                                                                .addComponent(jScrollPane1,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE,
                                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                                .addGap(0, 0, Short.MAX_VALUE)))
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(jBotoes, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addGap(387, 387, 387)))));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(Informacoes, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addGroup(layout.createSequentialGroup()
                                                .addGap(236, 236, 236)
                                                .addComponent(jBotoes, javax.swing.GroupLayout.PREFERRED_SIZE,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout
                                                .createSequentialGroup()
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                                .addComponent(lLocados)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED,
                                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 249,
                                                        javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                                .addComponent(botaoExcluir)
                                .addContainerGap()));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoExcluirActionPerformed
        int resposta = javax.swing.JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este cliente?",
                "Confirmação", javax.swing.JOptionPane.YES_NO_OPTION);
        if (resposta == javax.swing.JOptionPane.YES_OPTION) {
            // Lógica para excluir o cliente
            deletarCliente(telefone.getText());
            javax.swing.JOptionPane.showMessageDialog(this, "Reinicie a Tela Listar Dados.");
            this.dispose(); // Fecha a janela após a exclusão
        }
    }// GEN-LAST:event_botaoExcluirActionPerformed

    private void jTable1MouseClicked(java.awt.event.MouseEvent evt) {// GEN-FIRST:event_jTable1MouseClicked
        if (evt.getClickCount() == 2) {
            int viewRow = jTable1.getSelectedRow();
            if (viewRow == -1)
                return;

            int modelRow = jTable1.convertRowIndexToModel(viewRow);
            if (modelRow < 0 || modelRow >= cliente.getLocados().size())
                return;

            final dados.Produto p = cliente.getLocados().get(modelRow);
            // procura a venda correspondente
            Venda vEncontrada = null;
            for (Venda v : vendas) {
                if (v.getIdProduto().equals(p.getCodigo()) && v.getIdCliente().equals(cliente.getTelefone())) {
                    vEncontrada = v;
                    break;
                }
            }
            // abre a tela de venda se encontrada
            if (vEncontrada != null) {
                final Venda vendaFinal = vEncontrada;
                SwingUtilities.invokeLater(() -> {
                    VendaTela tela = new VendaTela(vendaFinal); // precisa ter um construtor que receba a Venda
                    tela.setLocationRelativeTo(null);
                    tela.setVisible(true);
                });
            } else {
                javax.swing.JOptionPane.showMessageDialog(this, "Nenhuma venda encontrada para este produto.");
            }
        }
    }// GEN-LAST:event_jTable1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteTela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Informacoes;
    private javax.swing.JLabel Multa;
    private javax.swing.JLabel atrasou;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JLabel endereco;
    private javax.swing.JPanel jBotoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    private javax.swing.JLabel lAtrasou;
    private javax.swing.JLabel lEndereco;
    private javax.swing.JLabel lLocados;
    private javax.swing.JLabel lMultaAtraso;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lTelefone;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel telefone;
    // End of variables declaration//GEN-END:variables
}
