/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEnd.telas;

/**
 *
 * @author gbert
 */
public class ClienteTela extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(ClienteTela.class.getName());

    /**
     * Creates new form Cliente
     */
    public ClienteTela() {
        initComponents();
    }

    public ClienteTela(dados.Cliente cliente) {
        initComponents();
        nome.setText(cliente.getNome());
        telefone.setText(cliente.getTelefone());
        endereco.setText(cliente.getEndereco());
        Multa.setText("R$ " + cliente.getMultaAtraso());
        atrasou.setText(cliente.getAtrasoDevol() ? "Sim" : "Não");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Informacoes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        lTelefone = new javax.swing.JLabel();
        telefone = new javax.swing.JLabel();
        lEndereco = new javax.swing.JLabel();
        endereco = new javax.swing.JLabel();
        lMultaAtraso = new javax.swing.JLabel();
        Multa = new javax.swing.JLabel();
        lAtrasou = new javax.swing.JLabel();
        atrasou = new javax.swing.JLabel();
        jBotoes = new javax.swing.JPanel();
        botaoExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Informacoes.setLayout(new java.awt.GridLayout(20, 0, 0, 3));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Informações:");
        Informacoes.add(jLabel1);

        lNome.setText("Nome:");
        Informacoes.add(lNome);

        nome.setText("jLabel10");
        Informacoes.add(nome);

        lTelefone.setText("Telefone: ");
        Informacoes.add(lTelefone);

        telefone.setText("jLabel11");
        Informacoes.add(telefone);

        lEndereco.setText("Endereco:");
        Informacoes.add(lEndereco);

        endereco.setText("jLabel12");
        Informacoes.add(endereco);

        lMultaAtraso.setText("Multa de atraso: ");
        Informacoes.add(lMultaAtraso);

        Multa.setText("jLabel16");
        Informacoes.add(Multa);

        lAtrasou.setText("Atrasou Devolução:");
        Informacoes.add(lAtrasou);

        atrasou.setText("jLabel3");
        Informacoes.add(atrasou);

        jBotoes.setLayout(new java.awt.GridLayout());

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        jBotoes.add(botaoExcluir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Informacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 388, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Informacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_botaoExcluirActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new ClienteTela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Informacoes;
    private javax.swing.JLabel Multa;
    private javax.swing.JLabel atrasou;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JLabel endereco;
    private javax.swing.JPanel jBotoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lAtrasou;
    private javax.swing.JLabel lEndereco;
    private javax.swing.JLabel lMultaAtraso;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lTelefone;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel telefone;
    // End of variables declaration//GEN-END:variables
}
