//Autores
//PEDRO LEONARDO S. DA S. DE O. PERES 
//LORENZO DE OLIVEIRA E SILVA 
//GABRIEL EVANGELISTA BERTOLINO DOS SANTOS



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEnd.telas;

import javax.swing.JOptionPane;

import dados.Game;
import frontEnd.formularios.FormularioEditarJogo;
import frontEnd.formularios.FormularioVenda;

import static ferramentas.CrudProduto.deletarProduto;
import static ferramentas.CrudProduto.encontrarProduto;

/**
 *
 * @author gbert
 */
public class JogoTela extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(JogoTela.class.getName());
    private FormularioVenda formVenda;
    /**
     * Creates new form Jogo
     */
    Game game;
    Runnable callback;

    public JogoTela() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    // construtor que preenche os labels com os dados do Game
    public JogoTela(Game g) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.game = g;
        if (g != null) {
            nome.setText(g.getNome());
            desenvolvedor.setText(g.getDesenvolvedor());
            publicadora.setText(g.getPublicadora());
            plataforma.setText(g.getPlataforma());
            clasInd.setText(g.getClassInd() == null ? "-" : g.getClassInd());
            estoque.setText(String.valueOf(g.getEstoque()));
            alugado.setText(g.estaAlugado() ? "Sim" : "Não");
            preco.setText("R$ " + g.getPreco());
            // botão "Alugar" só fica habilitado se não estiver alugado
            botaoAlugar.setEnabled(!game.estaAlugado() && game.getEstoque() > 0);
        }
    }
    // construtor que preenche os labels com os dados do Game e atualiza tabela
    public JogoTela(Game g, Runnable callback) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        this.game = g;
        this.callback = callback;
        if (g != null) {
            nome.setText(g.getNome());
            desenvolvedor.setText(g.getDesenvolvedor());
            publicadora.setText(g.getPublicadora());
            plataforma.setText(g.getPlataforma());
            clasInd.setText(g.getClassInd() == null ? "-" : g.getClassInd());
            estoque.setText(String.valueOf(g.getEstoque()));
            alugado.setText(g.estaAlugado() ? "Sim" : "Não");
            preco.setText("R$ " + g.getPreco());
            // botão "Alugar" só fica habilitado se não estiver alugado
            botaoAlugar.setEnabled(!game.estaAlugado() && game.getEstoque() > 0);
        }
    }

    private void atualizarDadosJogo() {
        this.game = (Game) encontrarProduto(this.game.getCodigo(), "jogos");
        if (this.game != null) {
            nome.setText(game.getNome());
            desenvolvedor.setText(game.getDesenvolvedor());
            publicadora.setText(game.getPublicadora());
            plataforma.setText(game.getPlataforma());
            clasInd.setText(game.getClassInd() == null ? "-" : game.getClassInd());
            estoque.setText(String.valueOf(game.getEstoque()));
            alugado.setText(game.estaAlugado() ? "Sim" : "Não");
            preco.setText("R$ " + game.getPreco());
            // botão "Alugar" só fica habilitado se não estiver alugado
            botaoAlugar.setEnabled(!game.estaAlugado() && game.getEstoque() > 0);
        }

        if (callback != null) {
            callback.run();
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Informacoes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        lDesenvolvedor = new javax.swing.JLabel();
        desenvolvedor = new javax.swing.JLabel();
        lPublicadora = new javax.swing.JLabel();
        publicadora = new javax.swing.JLabel();
        lPlataforma = new javax.swing.JLabel();
        plataforma = new javax.swing.JLabel();
        lClassInd = new javax.swing.JLabel();
        clasInd = new javax.swing.JLabel();
        lEstoque = new javax.swing.JLabel();
        estoque = new javax.swing.JLabel();
        lAlugado = new javax.swing.JLabel();
        alugado = new javax.swing.JLabel();
        lPreco = new javax.swing.JLabel();
        preco = new javax.swing.JLabel();
        jBotoes = new javax.swing.JPanel();
        botaoAlugar = new javax.swing.JButton();
        botaoEditar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Informacoes.setLayout(new java.awt.GridLayout(20, 0, 0, 3));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Informações:");
        Informacoes.add(jLabel1);

        lNome.setText("Nome:");
        Informacoes.add(lNome);

        nome.setText("jLabel10");
        Informacoes.add(nome);

        lDesenvolvedor.setText("Desenvolvedor:");
        Informacoes.add(lDesenvolvedor);

        desenvolvedor.setText("jLabel11");
        Informacoes.add(desenvolvedor);

        lPublicadora.setText("Publicadora: ");
        Informacoes.add(lPublicadora);

        publicadora.setText("jLabel12");
        Informacoes.add(publicadora);

        lPlataforma.setText("Plataforma: ");
        Informacoes.add(lPlataforma);

        plataforma.setText("jLabel16");
        Informacoes.add(plataforma);

        lClassInd.setText("Classificação Indicativa:");
        Informacoes.add(lClassInd);

        clasInd.setText("jLabel15");
        Informacoes.add(clasInd);

        lEstoque.setText("Estoque:");
        Informacoes.add(lEstoque);

        estoque.setText("jLabel14");
        Informacoes.add(estoque);

        lAlugado.setText("Esta alugado");
        Informacoes.add(lAlugado);

        alugado.setText("jLabel13");
        Informacoes.add(alugado);

        lPreco.setText("Preço");
        Informacoes.add(lPreco);

        preco.setText("jLabel17");
        Informacoes.add(preco);

        jBotoes.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        botaoAlugar.setText("Alugar");
        botaoAlugar.addActionListener(evt -> botaoAlugarActionPerformed(evt));
        jBotoes.add(botaoAlugar);

        botaoEditar.setText("Editar");
        botaoEditar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoEditarActionPerformed(evt);
            }
        });
        jBotoes.add(botaoEditar);

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        jBotoes.add(botaoExcluir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Informacoes, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 453,
                                                Short.MAX_VALUE))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(Informacoes, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jBotoes, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(23, Short.MAX_VALUE)));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoEditarActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoEditarActionPerformed
        FormularioEditarJogo tela = new FormularioEditarJogo(this.game, this::atualizarDadosJogo);
        tela.setLocationRelativeTo(null);
        tela.setVisible(true);
    }// GEN-LAST:event_botaoEditarActionPerformed

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoExcluirActionPerformed
        int resposta = JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este jogo?", "Confirmação",
                JOptionPane.YES_NO_OPTION);
        if (resposta == JOptionPane.YES_OPTION) {
            // Lógica para excluir o jogo
            deletarProduto(game.getCodigo(), "jogos");
            JOptionPane.showMessageDialog(this, "Reinicie a Tela Listar Dados.");
            if (callback != null) {
                callback.run();
            }
            this.dispose(); // Fecha a janela após a exclusão
        }
    }// GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoAlugarActionPerformed(java.awt.event.ActionEvent evt) {
        if (game.getEstoque() <= 0) {
            JOptionPane.showMessageDialog(this, "Estoque insuficiente para alugar este jogo.", "Erro",
                    JOptionPane.ERROR_MESSAGE);
            return;

        } else {
            formVenda = new FormularioVenda(this.game);
            formVenda.setVisible(true);
        }
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        // <editor-fold defaultstate="collapsed" desc=" Look and feel setting code
        // (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the default
         * look and feel.
         * For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        // </editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new JogoTela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Informacoes;
    private javax.swing.JLabel alugado;
    private javax.swing.JButton botaoAlugar;
    private javax.swing.JButton botaoEditar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JLabel clasInd;
    private javax.swing.JLabel desenvolvedor;
    private javax.swing.JLabel estoque;
    private javax.swing.JPanel jBotoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lAlugado;
    private javax.swing.JLabel lClassInd;
    private javax.swing.JLabel lDesenvolvedor;
    private javax.swing.JLabel lEstoque;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPlataforma;
    private javax.swing.JLabel lPreco;
    private javax.swing.JLabel lPublicadora;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel plataforma;
    private javax.swing.JLabel preco;
    private javax.swing.JLabel publicadora;
    // End of variables declaration//GEN-END:variables
}
