//Autores
//PEDRO LEONARDO S. DA S. DE O. PERES 
//LORENZO DE OLIVEIRA E SILVA 
//GABRIEL EVANGELISTA BERTOLINO DOS SANTOS



/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontEnd.telas;

import frontEnd.tabelas.TabelaCliente;
import frontEnd.tabelas.TabelaJogos;
import frontEnd.tabelas.TabelaVendas;
import frontEnd.tabelas.TabelaVideo;
import java.awt.CardLayout;
import java.util.ArrayList;

import dados.Cliente;
import dados.Game;
import dados.Produto;
import dados.Venda;
import dados.Video;

import static ferramentas.CrudCliente.listarCliente;
import static ferramentas.CrudProduto.listarProdutos;
import static ferramentas.CrudVendas.listarVendas;

/**
 *
 * @author gbert
 */
public class ListaDeDados extends javax.swing.JPanel {

    /**
     * Creates new form ListaDeDados
     */
    TabelaCliente tabelaCliente;
    TabelaJogos tabelaJogos;
    TabelaVideo tabelaVideo;
    TabelaVendas tabelaVendas;
    ArrayList<Game> listaDeJogos;
    ArrayList<Video> listaDeVideos;
    ArrayList<Cliente> listaDeClientes;
    ArrayList<Venda> listaDeVendas;

    public ListaDeDados() {
        initComponents();
        listaDeJogos = converteProdutoParaGame(listarProdutos("jogos"));
        listaDeVideos = converteProdutoParaVideo(listarProdutos("videos"));
        listaDeClientes = listarCliente();
        listaDeVendas = listarVendas();
        
        tabelaCliente = new TabelaCliente();
        tabelaJogos = new TabelaJogos();
        tabelaVideo = new TabelaVideo();
        tabelaVendas = new TabelaVendas();
    
        tabelaJogos.carregarJogos(listaDeJogos);
        tabelaVideo.carregarVideo(listaDeVideos);
        tabelaCliente.carregarClientes(listaDeClientes);
        tabelaVendas.carregarVendas(listaDeVendas);
        
        Container.add(tabelaVendas, "Vendas");
        Container.add(tabelaCliente, "Cliente");
        Container.add(tabelaJogos, "Jogos");
        Container.add(tabelaVideo, "Video");
    }

    public void atualizarListas() {
        listaDeJogos = converteProdutoParaGame(listarProdutos("jogos"));
        listaDeVideos = converteProdutoParaVideo(listarProdutos("videos"));
        listaDeClientes = listarCliente();
        listaDeVendas = listarVendas();

        tabelaJogos.carregarJogos(listaDeJogos);
        tabelaVideo.carregarVideo(listaDeVideos);
        tabelaCliente.carregarClientes(listaDeClientes);
        tabelaVendas.carregarVendas(listaDeVendas);
    }

    private ArrayList<Game> converteProdutoParaGame(ArrayList<Produto> produtos) {
        ArrayList<Game> jogos = new ArrayList<>();
        for (Produto p : produtos) {
            if (p instanceof Game) {
                jogos.add((Game) p);
            }
        }
        return jogos;
    }

    private ArrayList<Video> converteProdutoParaVideo(ArrayList<Produto> produtos) {
        ArrayList<Video> videos = new ArrayList<>();
        for (Produto p : produtos) {
            if (p instanceof Video) {
                videos.add((Video) p);
            }
        }
        return videos;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoesCliente = new javax.swing.JPanel();
        botaoAtualizarDados = new javax.swing.JButton();
        botaoVideo = new javax.swing.JButton();
        botaoJogo = new javax.swing.JButton();
        botaoCliente = new javax.swing.JButton();
        botaoVendas = new javax.swing.JButton();
        Container = new javax.swing.JPanel();

        botoesCliente.setBackground(new java.awt.Color(204, 204, 204));
        botoesCliente.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        botoesCliente.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        botaoAtualizarDados.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoAtualizarDados.setText("Atualizar Dados");
        botaoAtualizarDados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAtualizarDadosActionPerformed(evt);
            }
        });
        botoesCliente.add(botaoAtualizarDados);

        botaoVideo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoVideo.setText("Video");
        botaoVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVideoActionPerformed(evt);
            }
        });
        botoesCliente.add(botaoVideo);

        botaoJogo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoJogo.setText("Jogo");
        botaoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoJogoActionPerformed(evt);
            }
        });
        botoesCliente.add(botaoJogo);

        botaoCliente.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoCliente.setText("Cliente");
        botaoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClienteActionPerformed(evt);
            }
        });
        botoesCliente.add(botaoCliente);

        botaoVendas.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoVendas.setText("Vendas");
        botaoVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVendasActionPerformed(evt);
            }
        });
        botoesCliente.add(botaoVendas);

        Container.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(botoesCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 730, Short.MAX_VALUE)
                    .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(botoesCliente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE, 24, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void botaoJogoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoJogoActionPerformed
        CardLayout cl = (CardLayout) Container.getLayout();
        cl.show(Container, "Jogos");
    }// GEN-LAST:event_botaoJogoActionPerformed

    private void botaoVideoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoVideoActionPerformed
        CardLayout cl = (CardLayout) Container.getLayout();
        cl.show(Container, "Video");
    }// GEN-LAST:event_botaoVideoActionPerformed

    private void botaoClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoClienteActionPerformed
        CardLayout cl = (CardLayout) Container.getLayout();
        cl.show(Container, "Cliente");
    }// GEN-LAST:event_botaoClienteActionPerformed

    private void botaoVendasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoVendasActionPerformed
        CardLayout cl = (CardLayout) Container.getLayout();
        cl.show(Container, "Vendas");
    }// GEN-LAST:event_botaoVendasActionPerformed
    
    private void botaoAtualizarDadosActionPerformed(java.awt.event.ActionEvent evt){// GEN-FIRST:event_botaoAtualizarDadosActionPerformed
        atualizarListas();
    }// GEN-LAST:event_botaoAtualizarDadosActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton botaoAtualizarDados;
    private javax.swing.JButton botaoCliente;
    private javax.swing.JButton botaoJogo;
    private javax.swing.JButton botaoVendas;
    private javax.swing.JButton botaoVideo;
    private javax.swing.JPanel botoesCliente;
    // End of variables declaration//GEN-END:variables
}
