/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package frontEnd.telas;

import frontEnd.tabelas.TabelaCliente;
import frontEnd.tabelas.TabelaJogos;
import frontEnd.tabelas.TabelaVendas;
import frontEnd.tabelas.TabelaVideo;
import java.awt.CardLayout;
import java.util.ArrayList;

import dados.Cliente;
import dados.Game;
import dados.Venda;
import dados.Video;

/**
 *
 * @author gbert
 */
public class ListaDeDados extends javax.swing.JPanel {

    /**
     * Creates new form ListaDeDados
     */
    TabelaCliente tabelaCliente;
    TabelaJogos tabelaJogos;
    TabelaVideo tabelaVideo;
    TabelaVendas tabelaVendas;
    ArrayList<Game> listaDeJogos;
    ArrayList<Video> listaDeVideos;
    ArrayList<Cliente> listaDeClientes;
    ArrayList<Venda> listaDeVendas;

    public ListaDeDados() {
        initComponents();
        listaDeJogos = new ArrayList<Game>();
        listaDeVideos = new ArrayList<Video>();
        listaDeClientes = new ArrayList<Cliente>();
        // Exemplo de inicialização de lista de vendas
        listaDeVendas = new ArrayList<Venda>();
        listaDeJogos.add(new Game("The Witcher 3", "001", "18", "CD Projekt", "CD Projekt RED", "PC", false, 10, 5));
        listaDeJogos.add(new Game("God of War", "002", "16", "Sony", "Santa Monica Studio", "PS5", false, 20, 3));

        listaDeVideos.add(new Video("The Matrix", "01", "14", "Warner Bros.", "Warner Bros.", "Blu-Ray", "Filme", 136, false, 0L, 5L));

        listaDeVideos.add(new Video("Breaking Bad - Box 1", "02", "16", "High Bridge", "Sony Pictures", "DVD", "Série - Box", 600, false, 2L, 2L));

        listaDeClientes.add(new Cliente("Alice", "teste", "1234567"));
        listaDeClientes.add(new Cliente("Bob", "teste2", "9876543"));

        tabelaCliente = new TabelaCliente();
        tabelaJogos = new TabelaJogos();
        tabelaVideo = new TabelaVideo();
        tabelaVendas = new TabelaVendas();

        tabelaJogos.carregarJogos(listaDeJogos);
        tabelaVideo.carregarVideo(listaDeVideos);
        tabelaCliente.carregarClientes(listaDeClientes);

        
        Container.add(tabelaVendas, "Vendas");
        Container.add(tabelaCliente, "Cliente");
        Container.add(tabelaJogos, "Jogos");
        Container.add(tabelaVideo, "Video");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated
    // Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        botoesCliente = new javax.swing.JPanel();
        botaoVideo = new javax.swing.JButton();
        botaoJogo = new javax.swing.JButton();
        botaoCliente = new javax.swing.JButton();
        botaoVendas = new javax.swing.JButton();
        Container = new javax.swing.JPanel();

        botoesCliente.setBackground(new java.awt.Color(204, 204, 204));
        botoesCliente.setBorder(javax.swing.BorderFactory.createEmptyBorder(5, 5, 5, 5));
        botoesCliente.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        botaoVideo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoVideo.setText("Video");
        botaoVideo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVideoActionPerformed(evt);
            }
        });
        botoesCliente.add(botaoVideo);

        botaoJogo.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoJogo.setText("Jogo");
        botaoJogo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoJogoActionPerformed(evt);
            }
        });
        botoesCliente.add(botaoJogo);

        botaoCliente.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoCliente.setText("Cliente");
        botaoCliente.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoClienteActionPerformed(evt);
            }
        });
        botoesCliente.add(botaoCliente);

        botaoVendas.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        botaoVendas.setText("Vendas");
        botaoVendas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoVendasActionPerformed(evt);
            }
        });
        botoesCliente.add(botaoVendas);

        Container.setLayout(new java.awt.CardLayout());

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(botoesCliente, javax.swing.GroupLayout.DEFAULT_SIZE, 730,
                                                Short.MAX_VALUE)
                                        .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE,
                                                javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addContainerGap()));
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addComponent(botoesCliente, javax.swing.GroupLayout.PREFERRED_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Container, javax.swing.GroupLayout.DEFAULT_SIZE,
                                        javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addContainerGap()));
    }// </editor-fold>//GEN-END:initComponents

    private void botaoJogoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoJogoActionPerformed
        CardLayout cl = (CardLayout) Container.getLayout();
        cl.show(Container, "Jogos");
    }// GEN-LAST:event_botaoJogoActionPerformed

    private void botaoVideoActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoVideoActionPerformed
        CardLayout cl = (CardLayout) Container.getLayout();
        cl.show(Container, "Video");
    }// GEN-LAST:event_botaoVideoActionPerformed

    private void botaoClienteActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoClienteActionPerformed
        CardLayout cl = (CardLayout) Container.getLayout();
        cl.show(Container, "Cliente");
    }// GEN-LAST:event_botaoClienteActionPerformed

    private void botaoVendasActionPerformed(java.awt.event.ActionEvent evt) {// GEN-FIRST:event_botaoVendasActionPerformed
        CardLayout cl = (CardLayout) Container.getLayout();
        cl.show(Container, "Vendas");
    }// GEN-LAST:event_botaoVendasActionPerformed

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Container;
    private javax.swing.JButton botaoCliente;
    private javax.swing.JButton botaoJogo;
    private javax.swing.JButton botaoVendas;
    private javax.swing.JButton botaoVideo;
    private javax.swing.JPanel botoesCliente;
    // End of variables declaration//GEN-END:variables
}
