/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEnd.telas;

import dados.Cliente;
import dados.Game;
import dados.Produto;
import dados.Venda;
import dados.Video;

import static ferramentas.CrudCliente.encontrarCliente;
import static ferramentas.CrudProduto.encontrarProduto;

import java.util.logging.Level;

/**
 *
 * @author gbert
 */
public class VendaTela extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VendaTela.class.getName());

    /**
     * Creates new form VendaTela
     */
    public VendaTela() {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    public VendaTela(Venda v) {
        initComponents();
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        
        idVenda.setText(v.getCodigo());
        codigoProduto.setText(v.getIdProduto());
        telefoneCliente.setText(v.getIdCliente());
        dataLocacao.setText(v.getDataLocar());
        dataDevolicao.setText(v.getDataDevol());
        valor.setText(Double.toString(v.getValorTotal()));
        
        Cliente c = encontrarCliente(v.getIdCliente());
        if (c != null) {
            nomeCliente.setText(c.getNome());
            enderecoCliente.setText(c.getEndereco());
        } else {
            nomeCliente.setText("Cliente não encontrado");
            enderecoCliente.setText("Cliente não encontrado");
        }
        
        Produto p = encontrarProduto(v.getIdProduto(), v.getColecao());
        if (p != null) {
            nomeProduto.setText(p.getNome());
        } else {
            nomeProduto.setText("Produto não encontrado");
        }

    }

    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Informacoes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lidVenda = new javax.swing.JLabel();
        idVenda = new javax.swing.JLabel();
        lCodigoProduto = new javax.swing.JLabel();
        codigoProduto = new javax.swing.JLabel();
        lNomeProduto = new javax.swing.JLabel();
        nomeProduto = new javax.swing.JLabel();
        lTelefoneCliente = new javax.swing.JLabel();
        telefoneCliente = new javax.swing.JLabel();
        lNomeCliente = new javax.swing.JLabel();
        nomeCliente = new javax.swing.JLabel();
        lEnderecoCliente = new javax.swing.JLabel();
        enderecoCliente = new javax.swing.JLabel();
        lDataLocacao = new javax.swing.JLabel();
        dataLocacao = new javax.swing.JLabel();
        lDataDevolucao = new javax.swing.JLabel();
        dataDevolicao = new javax.swing.JLabel();
        lValor = new javax.swing.JLabel();
        valor = new javax.swing.JLabel();
        jBotoes = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Informacoes.setLayout(new java.awt.GridLayout(19, 0, 0, 3));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Informações:");
        Informacoes.add(jLabel1);

        lidVenda.setText("ID:");
        Informacoes.add(lidVenda);

        idVenda.setText("info");
        Informacoes.add(idVenda);

        lCodigoProduto.setText("Codigo do produto");
        Informacoes.add(lCodigoProduto);

        codigoProduto.setText("info");
        Informacoes.add(codigoProduto);

        lNomeProduto.setText("Nome do Produto");
        Informacoes.add(lNomeProduto);

        nomeProduto.setText("info");
        Informacoes.add(nomeProduto);

        lTelefoneCliente.setText("Telefone do cliente: ");
        Informacoes.add(lTelefoneCliente);

        telefoneCliente.setText("info");
        Informacoes.add(telefoneCliente);

        lNomeCliente.setText("Nome do Cliente");
        Informacoes.add(lNomeCliente);

        nomeCliente.setText("info");
        Informacoes.add(nomeCliente);

        lEnderecoCliente.setText("Endereço do Cliente:");
        Informacoes.add(lEnderecoCliente);

        enderecoCliente.setText("info");
        Informacoes.add(enderecoCliente);

        lDataLocacao.setText("Data da locação");
        Informacoes.add(lDataLocacao);

        dataLocacao.setText("info");
        Informacoes.add(dataLocacao);

        lDataDevolucao.setText("Data de devolução");
        Informacoes.add(lDataDevolucao);

        dataDevolicao.setText("info");
        Informacoes.add(dataDevolicao);

        lValor.setText("Valor da venda");
        Informacoes.add(lValor);

        valor.setText("info");
        Informacoes.add(valor);

        jBotoes.setLayout(new java.awt.GridLayout(1, 0, 5, 0));

        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setText("Devolução");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jBotoes.add(jButton1);

        botaoExcluir.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        jBotoes.add(botaoExcluir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(Informacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 398, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(17, 17, 17)
                .addComponent(Informacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(20, 20, 20)
                .addComponent(jBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VendaTela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Informacoes;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JLabel codigoProduto;
    private javax.swing.JLabel dataDevolicao;
    private javax.swing.JLabel dataLocacao;
    private javax.swing.JLabel enderecoCliente;
    private javax.swing.JLabel idVenda;
    private javax.swing.JPanel jBotoes;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lCodigoProduto;
    private javax.swing.JLabel lDataDevolucao;
    private javax.swing.JLabel lDataLocacao;
    private javax.swing.JLabel lEnderecoCliente;
    private javax.swing.JLabel lNomeCliente;
    private javax.swing.JLabel lNomeProduto;
    private javax.swing.JLabel lTelefoneCliente;
    private javax.swing.JLabel lValor;
    private javax.swing.JLabel lidVenda;
    private javax.swing.JLabel nomeCliente;
    private javax.swing.JLabel nomeProduto;
    private javax.swing.JLabel telefoneCliente;
    private javax.swing.JLabel valor;
    // End of variables declaration//GEN-END:variables
}
