/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package frontEnd.telas;

import dados.Video;
import frontEnd.formularios.FormularioVenda;

import static ferramentas.CrudProduto.deletarProduto;

/**
 *
 * @author gbert
 */
public class VideoTela extends javax.swing.JFrame {

    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(VideoTela.class.getName());
    private FormularioVenda formVenda;
    Video video;
    /**
     * Creates new form Video
     */
    public VideoTela() {
        initComponents();
    }

    public VideoTela(Video video) {
        initComponents();
        this.video = video;
        nome.setText(video.getNome());
        estudio.setText(video.getEstudio());
        distribuidora.setText(video.getDistribuidora());
        tipoMidia.setText(video.getTipoMidia());
        duracao.setText(String.valueOf(video.getDuracao()));
        clasInd.setText(video.getClassInd());
        estoque.setText(String.valueOf(video.getEstoque()));
        alugado.setText(video.estaAlugado() ? "Sim" : "Não");
        preco.setText("R$ " + video.getPreco());
        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        Informacoes = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        lNome = new javax.swing.JLabel();
        nome = new javax.swing.JLabel();
        lEstudio = new javax.swing.JLabel();
        estudio = new javax.swing.JLabel();
        lDistribuidora = new javax.swing.JLabel();
        distribuidora = new javax.swing.JLabel();
        lTipoMidia = new javax.swing.JLabel();
        tipoMidia = new javax.swing.JLabel();
        lDuracao = new javax.swing.JLabel();
        duracao = new javax.swing.JLabel();
        lClassInd = new javax.swing.JLabel();
        clasInd = new javax.swing.JLabel();
        lEstoque = new javax.swing.JLabel();
        estoque = new javax.swing.JLabel();
        lAlugado = new javax.swing.JLabel();
        alugado = new javax.swing.JLabel();
        lPreco = new javax.swing.JLabel();
        preco = new javax.swing.JLabel();
        jBotoes = new javax.swing.JPanel();
        botaoAlugar = new javax.swing.JButton();
        botaoExcluir = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        Informacoes.setLayout(new java.awt.GridLayout(22, 0, 0, 3));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 15)); // NOI18N
        jLabel1.setText("Informações:");
        Informacoes.add(jLabel1);

        lNome.setText("Nome:");
        Informacoes.add(lNome);

        nome.setText("jLabel10");
        Informacoes.add(nome);

        lEstudio.setText("Estudio:");
        Informacoes.add(lEstudio);

        estudio.setText("jLabel11");
        Informacoes.add(estudio);

        lDistribuidora.setText("Distribuidora: ");
        Informacoes.add(lDistribuidora);

        distribuidora.setText("jLabel12");
        Informacoes.add(distribuidora);

        lTipoMidia.setText("Tipo de Midia");
        Informacoes.add(lTipoMidia);

        tipoMidia.setText("jLabel4");
        Informacoes.add(tipoMidia);

        lDuracao.setText("Duração:");
        Informacoes.add(lDuracao);

        duracao.setText("jLabel5");
        Informacoes.add(duracao);

        lClassInd.setText("Classificação Indicativa:");
        Informacoes.add(lClassInd);

        clasInd.setText("jLabel15");
        Informacoes.add(clasInd);

        lEstoque.setText("Estoque:");
        Informacoes.add(lEstoque);

        estoque.setText("jLabel14");
        Informacoes.add(estoque);

        lAlugado.setText("Esta alugado");
        Informacoes.add(lAlugado);

        alugado.setText("jLabel13");
        Informacoes.add(alugado);

        lPreco.setText("Preço");
        Informacoes.add(lPreco);

        preco.setText("jLabel17");
        Informacoes.add(preco);

        jBotoes.setLayout(new java.awt.GridLayout());

        botaoAlugar.setText("Alugar");
        botaoAlugar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoAlugarActionPerformed(evt);
            }
        });
        jBotoes.add(botaoAlugar);

        botaoExcluir.setText("Excluir");
        botaoExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                botaoExcluirActionPerformed(evt);
            }
        });
        jBotoes.add(botaoExcluir);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(Informacoes, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jBotoes, javax.swing.GroupLayout.DEFAULT_SIZE, 623, Short.MAX_VALUE))
                                .addContainerGap())
        );
        layout.setVerticalGroup(
                layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                                .addGap(17, 17, 17)
                                .addComponent(Informacoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(20, 20, 20)
                                .addComponent(jBotoes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void botaoExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_botaoExcluirActionPerformed
        int resposta = javax.swing.JOptionPane.showConfirmDialog(this, "Tem certeza que deseja excluir este vídeo?", "Confirmação", javax.swing.JOptionPane.YES_NO_OPTION);
        if (resposta == javax.swing.JOptionPane.YES_OPTION) {
            // Lógica para excluir o vídeo
            deletarProduto(nome.getText(), "videos");
            javax.swing.JOptionPane.showMessageDialog(this, "Reinicie a Tela Listar Dados.");
            this.dispose(); // Fecha a janela após a exclusão
        }
    }//GEN-LAST:event_botaoExcluirActionPerformed

    private void botaoAlugarActionPerformed(java.awt.event.ActionEvent evt) {
        formVenda = new FormularioVenda(this.video);
        formVenda.setVisible(true);
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new VideoTela().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Informacoes;
    private javax.swing.JLabel alugado;
    private javax.swing.JButton botaoAlugar;
    private javax.swing.JButton botaoExcluir;
    private javax.swing.JLabel clasInd;
    private javax.swing.JLabel distribuidora;
    private javax.swing.JLabel duracao;
    private javax.swing.JLabel estoque;
    private javax.swing.JLabel estudio;
    private javax.swing.JPanel jBotoes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lAlugado;
    private javax.swing.JLabel lClassInd;
    private javax.swing.JLabel lDistribuidora;
    private javax.swing.JLabel lDuracao;
    private javax.swing.JLabel lEstoque;
    private javax.swing.JLabel lEstudio;
    private javax.swing.JLabel lNome;
    private javax.swing.JLabel lPreco;
    private javax.swing.JLabel lTipoMidia;
    private javax.swing.JLabel nome;
    private javax.swing.JLabel preco;
    private javax.swing.JLabel tipoMidia;
    // End of variables declaration//GEN-END:variables
}
